#!/bin/sh
########################################################################################################################
# This installation script helps you install, configure,                                                               #
# build and set up the application using Docker for local development.                                                 #
# It can also help with your CI&CD settings.                                                                           #
########################################################################################################################

# Load envs
. .env

# Dependencies
composer install --no-interaction --no-ansi --prefer-dist --no-suggest --no-progress --optimize-autoloader || { echo '"composer install" failed'; exit 1; }

# Build project assets
#yarn install --no-progress --non-interactive || { echo '"yarn install" failed'; exit 1; }
#yarn run encore dev # || { echo '"yarn run encore dev" failed'; exit 1; } # Or production

exit 0
