<?php

declare(strict_types=1);

namespace App\Web\AdminModule\Presenter;

use Doctrine\ORM\AbstractQuery;
use App\Domain\Category\Category;
use Doctrine\ORM\EntityManagerInterface;

final class DashboardPresenter extends AdminPresenter
{
	/** @var \Doctrine\ORM\EntityManagerInterface @inject */
	public EntityManagerInterface $em;

	protected function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub

		$r = $this->em->createQueryBuilder()
			->select('c, ct')
			->from(Category::class, 'c')
			->leftJoin('c.translations', 'ct')
			->getQuery()
			->getResult(AbstractQuery::HYDRATE_ARRAY);

		bdump($r);
	}
}
