<?php

declare(strict_types=1);

namespace App\Domain\Project;

use App\Domain\CookieProvider\ValueObject\CookieProviderId;

final class ProjectHasCookieProvider
{
    # autogenerated
    private string $id;

    private Project $project;

    private CookieProviderId $cookieProviderId;

    private function __construct() {}

    public static function create(Project $project, CookieProviderId $cookieProviderId): self
    {
        $association = new self();
        $association->project = $project;
        $association->cookieProviderId = $cookieProviderId;

        return $association;
    }

    public function cookieProviderId(): CookieProviderId
    {
        return $this->cookieProviderId;
    }
}
