<?php

declare(strict_types=1);

namespace App\Domain\Cookie;

use App\Domain\Cookie\ValueObject\Purpose;
use App\Domain\Shared\ValueObject\Locale;

final class CookieTranslation
{
    # autogenerated
    private string $id;

    private Cookie $cookie;

    private Locale $locale;

    private Purpose $purpose;

    private function __construct() {}

    public static function create(Cookie $cookie, Locale $locale, Purpose $purpose): self
    {
        $cookieTranslation = new self();
        $cookieTranslation->cookie = $cookie;
        $cookieTranslation->locale = $locale;
        $cookieTranslation->purpose = $purpose;

        return $cookieTranslation;
    }

    public function cookie(): Cookie
    {
        return $this->cookie;
    }

    public function locale(): Locale
    {
        return $this->locale;
    }

    public function purpose(): Purpose
    {
        return $this->purpose;
    }

    public function setPurpose(Purpose $purpose): void
    {
        $this->purpose = $purpose;
    }
}
