<?php

declare(strict_types=1);

namespace App\Domain\Category;

use App\Domain\Category\ValueObject\Name;
use App\Domain\Shared\ValueObject\Locale;

final class CategoryTranslation
{
    # autogenerated
    private string $id;

    private Category $category;

    private Locale $locale;

    private Name $name;

    private function __construct() {}

    public static function create(Category $category, Locale $locale, Name $name): self
    {
        $categoryTranslation = new self();
        $categoryTranslation->category = $category;
        $categoryTranslation->locale = $locale;
        $categoryTranslation->name = $name;

        return $categoryTranslation;
    }

    public function category(): Category
    {
        return $this->category;
    }

    public function locale(): Locale
    {
        return $this->locale;
    }

    public function name(): Name
    {
        return $this->name;
    }

    public function setName(Name $name): void
    {
        $this->name = $name;
    }
}
